GET http://localhost:5259/games

###
GET http://localhost:5259/games/1


###
POST http://localhost:5259/games
Content-Type: application/json

{
    "name": "갤러그",
    "genreId": 2,
    "price": 10000,
    "releaseDate": "1981-02-01"
}

###
PUT http://localhost:5259/games/1
Content-Type: application/json

{
    "id": 1,
    "name": "Street Fighter II Turbo",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1991-02-01"
}

###
DELETE http://localhost:5259/games/2